data:
  dataset: "iris"
model:
  type: "RandomForest"
  parameters:
    n_estimators: 100
    max_depth: 4

train:
  test_size: 0.2
  random_state: 42
output:
  model_path: "models/random_forest_model.pkl"